# Initial Data Load
Check if data loads easily, and check data cleaning steps are needed

In [1]:
import pandas as pd

## Secom Features dataset
Visual inspection indicates that the file is space delimited with no headers

In [7]:
secom_x = pd.read_csv("../data/secom.data", delimiter=" ", header=None)

In [8]:
secom_x

,0,1,2,3,4,5,6,7,8,9,...,580,581,582,583,584,585,586,587,588,589
0,3030.93,2564.00,2187.7333,1411.1265,1.3602,100.0,97.6133,0.1242,1.5005,0.0162,...,NaN,NaN,0.5005,0.0118,0.0035,2.3630,NaN,NaN,NaN,NaN
1,3095.78,2465.14,2230.4222,1463.6606,0.8294,100.0,102.3433,0.1247,1.4966,-0.0005,...,0.0060,208.2045,0.5019,0.0223,0.0055,4.4447,0.0096,0.0201,0.0060,208.2045
2,2932.61,2559.94,2186.4111,1698.0172,1.5102,100.0,95.4878,0.1241,1.4436,0.0041,...,0.0148,82.8602,0.4958,0.0157,0.0039,3.1745,0.0584,0.0484,0.0148,82.8602
3,2988.72,2479.90,2199.0333,909.7926,1.3204,100.0,104.2367,0.1217,1.4882,-0.0124,...,0.0044,73.8432,0.4990,0.0103,0.0025,2.0544,0.0202,0.0149,0.0044,73.8432
4,3032.24,2502.87,2233.3667,1326.5200,1.5334,100.0,100.3967,0.1235,1.5031,-0.0031,...,NaN,NaN,0.4800,0.4766,0.1045,99.3032,0.0202,0.0149,0.0044,73.8432
5,2946.25,2432.84,2233.3667,1326.5200,1.5334,100.0,100.3967,0.1235,1.5287,0.0167,...,0.0052,44.0077,0.4949,0.0189,0.0044,3.8276,0.0342,0.0151,0.0052,44.0077
6,3030.27,2430.12,2230.4222,1463.6606,0.8294,100.0,102.3433,0.1247,1.5816,-0.0270,...,NaN,NaN,0.5010,0.0143,0.0042,2.8515,0.0342,0.0151,0.0052,44.0077
7,3058.88,2690.15,2248.9000,1004.4692,0.7884,100.0,106.2400,0.1185,1.5153,0.0157,...,0.0063,95.0310,0.4984,0.0106,0.0034,2.1261,0.0204,0.0194,0.0063,95.0310
8,2967.68,2600.47,2248.9000,1004.4692,0.7884,100.0,106.2400,0.1185,1.5358,0.0111,...,0.0045,111.6525,0.4993,0.0172,0.0046,3.4456,0.0111,0.0124,0.0045,111.6525
9,3016.11,2428.37,2248.9000,1004.4692,0.7884,100.0,106.2400,0.1185,1.5381,0.0159,...,0.0073,90.2294,0.4967,0.0152,0.0038,3.0687,0.0212,0.0191,0.0073,90.2294
10,2994.05,2548.21,2195.1222,1046.1468,1.3204,100.0,103.3400,0.1223,1.5144,-0.0190,...,0.0071,57.8122,0.4925,0.0158,0.0041,3.2115,0.0355,0.0205,0.0071,57.8122
11,2928.84,2479.40,2196.2111,1605.7578,0.9959,100.0,97.9156,0.1257,1.4690,0.0170,...,0.0081,75.5077,0.4987,0.0427,0.0092,8.5646,0.0370,0.0279,0.0081,75.5077
12,2920.07,2507.40,2195.1222,1046.1468,1.3204,100.0,103.3400,0.1223,1.5310,-0.0259,...,0.0034,52.2039,0.4950,0.0153,0.0041,3.0926,0.0188,0.0098,0.0034,52.2039
13,3051.44,2529.27,2184.4333,877.6266,1.4668,100.0,107.8711,0.1240,1.5236,-0.0209,...,NaN,NaN,0.5034,0.0151,0.0038,3.0063,0.0188,0.0098,0.0034,52.2039
14,2963.97,2629.48,2224.6222,947.7739,1.2924,100.0,104.8489,0.1197,1.4474,0.0144,...,0.0084,142.9080,0.5077,0.0094,0.0026,1.8483,0.0202,0.0289,0.0084,142.9080
15,2988.31,2546.26,2224.6222,947.7739,1.2924,100.0,104.8489,0.1197,1.5465,0.0250,...,0.0045,100.2745,0.5058,0.0078,0.0021,1.5352,0.0174,0.0174,0.0045,100.2745
16,3028.02,2560.87,2270.2556,1258.4558,1.3950,100.0,104.8078,0.1207,1.4368,0.0150,...,0.0042,82.0989,0.5005,0.0108,0.0034,2.1574,0.0184,0.0151,0.0042,82.0989
17,3032.73,2517.79,2270.2556,1258.4558,1.3950,100.0,104.8078,0.1207,1.5537,0.0220,...,NaN,NaN,0.5015,0.0105,0.0027,2.0979,0.0184,0.0151,0.0042,82.0989
18,3040.34,2501.16,2207.3889,962.5317,1.2043,100.0,104.0311,0.1210,1.5481,-0.0367,...,NaN,NaN,0.4948,0.0117,0.0034,2.3737,0.0184,0.0151,0.0042,82.0989
19,2988.30,2519.05,2208.8556,1157.7224,1.5509,100.0,107.8022,0.1233,1.5362,-0.0259,...,0.0032,47.1586,0.5036,0.0169,0.0039,3.3514,0.0229,0.0108,0.0032,47.1586
20,2987.32,2528.81,NaN,NaN,NaN,NaN,NaN,0.1195,1.6343,-0.0263,...,NaN,NaN,0.5011,0.0117,0.0033,2.3308,0.0229,0.0108,0.0032,47.1586
21,NaN,2481.85,2207.3889,962.5317,1.2043,100.0,104.0311,0.1210,1.5559,0.0002,...,0.0023,34.4153,0.4947,0.0137,0.0041,2.7729,0.0175,0.0060,0.0023,34.4153
22,3002.27,2497.45,2207.3889,962.5317,1.2043,100.0,104.0311,0.1210,1.5465,0.0195,...,0.0075,114.5979,0.4977,0.0114,0.0037,2.2849,0.0250,0.0286,0.0075,114.5979
23,2884.74,2514.54,2160.3667,899.9488,1.4022,100.0,105.4978,0.1240,1.5585,-0.0317,...,0.0077,216.8869,0.4982,0.0099,0.0027,1.9771,0.0098,0.0213,0.0077,216.8869
24,3010.41,2632.80,2203.9000,1116.4129,1.2639,100.0,102.2733,0.1199,1.4227,0.0194,...,0.0101,125.0600,0.5032,0.0159,0.0039,3.1576,0.0288,0.0361,0.0101,125.0600
25,2979.74,2446.56,2257.1667,1437.9565,1.4918,100.0,106.3400,0.1203,1.5136,0.0018,...,NaN,NaN,0.5012,0.0336,0.0072,6.7053,0.0288,0.0361,0.0101,125.0600
26,3067.35,2456.33,2257.1667,1437.9565,1.4918,100.0,106.3400,0.1203,1.4860,-0.0019,...,NaN,NaN,0.5006,0.0083,0.0022,1.6593,0.0288,0.0361,0.0101,125.0600
27,2988.99,2607.63,2223.0333,1533.9934,1.3548,100.0,109.7067,0.1211,1.5582,-0.0101,...,0.0116,216.9552,0.5069,0.0158,0.0040,3.1232,0.0183,0.0397,0.0116,216.9552
28,2972.78,2431.57,2190.4889,1059.4390,0.8614,100.0,102.1178,0.1216,1.5438,0.0065,...,0.0053,127.5067,0.5036,0.0137,0.0036,2.7205,0.0130,0.0165,0.0053,127.5067
29,2981.85,2529.11,2180.3778,1208.7411,1.2998,100.0,100.2789,0.1209,1.4200,-0.0016,...,0.0062,146.8715,0.5019,0.0139,0.0034,2.7747,0.0121,0.0178,0.0062,146.8715
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1537,3006.22,2525.20,2192.7889,1268.5852,1.9935,100.0,104.5867,0.1268,1.4522,-0.0039,...,NaN,NaN,0.4942,0.0175,0.0045,3.5322,0.0199,0.0097,0.0037,48.7045
1538,3128.11,2367.16,2223.5333,1352.1869,0.8714,100.0,97.2189,0.1196,1.3907,0.0074,...,0.0038,47.3376,0.4977,0.0144,0.0037,2.9002,0.0237,0.0112,0.0038,47.3376
1539,2908.94,2560.99,2187.3444,2882.8558,1.5876,100.0,85.4189,0.1235,1.4167,0.0041,...,NaN,NaN,0.4987,0.0118,0.0028,2.3583,0.0237,0.0112,0.0038,47.3376
1540,2996.04,2555.92,2190.7666,3530.2362,0.8017,100.0,83.8767,0.1249,1.4158,-0.0029,...,0.0046,67.6676,0.5011,0.0163,0.0035,3.2608,0.0181,0.0123,0.0046,67.6676
1541,3246.31,2499.79,2216.8111,1190.4067,2.5148,100.0,114.5533,0.1230,1.3966,-0.0057,...,0.0019,23.5979,0.5021,0.0103,0.0030,2.0418,0.0266,0.0063,0.0019,23.5979
1542,2965.57,2487.91,2210.3556,910.7177,1.6941,100.0,119.8822,0.1268,1.3109,0.0174,...,0.0087,121.9426,0.4992,0.0136,0.0037,2.7204,0.0216,0.0263,0.0087,121.9426
1543,3109.18,2447.97,2210.3556,910.7177,1.6941,100.0,119.8822,0.1268,1.3502,0.0201,...,0.0055,50.8827,0.4975,0.0109,0.0038,2.1905,0.0273,0.0139,0.0055,50.8827
1544,3108.98,2537.73,2210.3556,910.7177,1.6941,100.0,119.8822,0.1268,1.2901,0.0202,...,0.0039,72.9676,0.4986,0.0192,0.0046,3.8442,0.0172,0.0126,0.0039,72.9676
1545,3100.19,2490.60,2212.8445,1068.5644,1.7835,100.0,113.8833,0.1249,1.4294,-0.0014,...,0.0070,402.6874,0.4951,0.0165,0.0051,3.3383,0.0063,0.0252,0.0070,402.6874
1546,3093.24,2488.18,2212.8445,1068.5644,1.7835,100.0,113.8833,0.1249,1.3482,0.0060,...,0.0047,105.7142,0.5022,0.0249,0.0049,4.9623,0.0134,0.0142,0.0047,105.7142
1547,3008.77,2542.36,2167.4222,2837.8788,1.4892,100.0,83.8222,0.1255,1.2895,0.0023,...,0.0022,36.2975,0.5012,0.0160,0.0044,3.2008,0.0222,0.0080,0.0022,36.2975
1548,3027.01,2464.98,2212.6334,1081.5662,1.0096,100.0,113.4278,0.1253,1.4410,0.0035,...,0.0071,88.5812,0.4944,0.0171,0.0040,3.4656,0.0253,0.0224,0.0071,88.5812
1549,3183.63,2498.00,2195.4444,2914.1792,1.5978,100.0,85.1011,0.1235,1.4129,-0.0081,...,NaN,NaN,0.5037,0.0117,0.0030,2.3203,0.0253,0.0224,0.0071,88.5812
1550,3072.20,2406.47,2195.4444,2914.1792,1.5978,100.0,85.1011,0.1235,1.3148,-0.0024,...,0.0022,27.5514,0.5034,0.0178,0.0043,3.5459,0.0236,0.0065,0.0022,27.5514
1551,2958.43,2489.06,2192.7556,867.3027,1.7393,100.0,123.4244,0.1251,1.4386,-0.0179,...,0.0044,30.7574,0.4972,0.0157,0.0040,3.1578,0.0400,0.0123,0.0044,30.7574
1552,2939.35,2521.98,2195.1000,1526.4440,0.8279,100.0,96.3100,0.1203,1.4366,0.0083,...,0.0074,247.6285,0.5031,0.0111,0.0028,2.2144,0.0085,0.0212,0.0074,247.6285
1553,3020.79,2500.19,2210.3556,910.7177,1.6941,100.0,119.8822,0.1268,1.3405,0.0201,...,0.0077,134.3983,0.4985,0.0126,0.0036,2.5295,0.0174,0.0234,0.0077,134.3983
1554,3031.78,2528.55,2182.5555,1261.0898,1.2110,100.0,112.2922,0.1252,1.3485,0.0151,...,0.0098,117.0945,0.5025,0.0138,0.0039,2.7512,0.0235,0.0275,0.0098,117.0945
1555,2902.96,2515.03,2181.1889,1338.8895,2.1195,100.0,108.1400,0.1263,1.3255,-0.0052,...,0.0051,184.8703,0.5002,0.0130,0.0035,2.5982,0.0086,0.0160,0.0051,184.8703
1556,3025.21,2503.30,2179.7333,3085.3781,1.4843,100.0,82.2467,0.1248,1.3687,-0.0070,...,0.0016,46.1076,0.5019,0.0158,0.0043,3.1428,0.0120,0.0055,0.0016,46.1076
1557,3072.10,2534.87,2177.4333,2945.8855,1.3321,100.0,83.1700,0.1253,1.4359,-0.0114,...,0.0023,26.7330,0.5010,0.0132,0.0035,2.6249,0.0277,0.0074,0.0023,26.7330
1558,3012.30,2466.84,2217.4111,1032.2836,1.4802,100.0,101.3511,0.1195,1.3832,0.0042,...,0.0054,176.6783,0.4993,0.0130,0.0037,2.5976,0.0097,0.0172,0.0054,176.6783
1559,3076.33,2456.13,2217.4111,1032.2836,1.4802,100.0,101.3511,0.1195,1.3120,-0.0043,...,0.0057,117.4564,0.4960,0.0157,0.0036,3.1743,0.0150,0.0176,0.0057,117.4564
1560,2770.40,2549.42,2204.2889,2637.9989,1.5549,100.0,86.1089,0.1234,1.2811,0.0037,...,0.0042,127.3154,0.5009,0.0155,0.0036,3.0997,0.0105,0.0133,0.0042,127.3154
1561,2951.14,2326.59,2212.6334,1081.5662,1.0096,100.0,113.4278,0.1253,1.4492,-0.0134,...,0.0051,46.4573,0.4965,0.0118,0.0032,2.3817,0.0320,0.0148,0.0051,46.4573
1562,2899.41,2464.36,2179.7333,3085.3781,1.4843,100.0,82.2467,0.1248,1.3424,-0.0045,...,0.0047,203.1720,0.4988,0.0143,0.0039,2.8669,0.0068,0.0138,0.0047,203.1720
1563,3052.31,2522.55,2198.5667,1124.6595,0.8763,100.0,98.4689,0.1205,1.4333,-0.0061,...,NaN,NaN,0.4975,0.0131,0.0036,2.6238,0.0068,0.0138,0.0047,203.1720
1564,2978.81,2379.78,2206.3000,1110.4967,0.8236,100.0,99.4122,0.1208,NaN,NaN,...,0.0025,43.5231,0.4987,0.0153,0.0041,3.0590,0.0197,0.0086,0.0025,43.5231
1565,2894.92,2532.01,2177.0333,1183.7287,1.5726,100.0,98.7978,0.1213,1.4622,-0.0072,...,0.0075,93.4941,0.5004,0.0178,0.0038,3.5662,0.0262,0.0245,0.0075,93.4941
1566,2944.92,2450.76,2195.4444,2914.1792,1.5978,100.0,85.1011,0.1235,NaN,NaN,...,0.0045,137.7844,0.4987,0.0181,0.0040,3.6275,0.0117,0.0162,0.0045,137.7844

In [13]:
# Inspect first row
secom_x.iloc[0,:]

0      3030.9300
1      2564.0000
2      2187.7333
3      1411.1265
4         1.3602
5       100.0000
6        97.6133
7         0.1242
8         1.5005
9         0.0162
10       -0.0034
11        0.9455
12      202.4396
13        0.0000
14        7.9558
15      414.8710
16       10.0433
17        0.9680
18      192.3963
19       12.5190
20        1.4026
21    -5419.0000
22     2916.5000
23    -4043.7500
24      751.0000
25        0.8955
26        1.7730
27        3.0490
28       64.2333
29        2.0222
         ...
560       0.1039
561      42.3877
562          NaN
563          NaN
564          NaN
565          NaN
566          NaN
567          NaN
568          NaN
569          NaN
570     533.8500
571       2.1113
572       8.9500
573       0.3157
574       3.0624
575       0.1026
576       1.6765
577      14.9509
578          NaN
579          NaN
580          NaN
581          NaN
582       0.5005
583       0.0118
584       0.0035
585       2.3630
586          NaN
587          NaN
588          NaN
589          NaN
Name: 0, Length: 590, dtype: float64

In [14]:
# Ensure that loaded shape matches size on website (1567 rows x 591 columns)
# The extra column missing here is the time column in labels dataset
secom_x.shape

(1567, 590)

## Secom Labels dataset
Load labels dataset

In [15]:
secom_y = pd.read_csv("../data/secom_labels.data", delimiter=" ", header=None)

In [16]:
secom_y

      0                    1
0    -1  19/07/2008 11:55:00
1    -1  19/07/2008 12:32:00
2     1  19/07/2008 13:17:00
3    -1  19/07/2008 14:43:00
4    -1  19/07/2008 15:22:00
5    -1  19/07/2008 17:53:00
6    -1  19/07/2008 19:44:00
7    -1  19/07/2008 19:45:00
8    -1  19/07/2008 20:24:00
9    -1  19/07/2008 21:35:00
10    1  19/07/2008 21:57:00
11    1  19/07/2008 22:52:00
12   -1  20/07/2008 03:35:00
13   -1  21/07/2008 08:21:00
14    1  21/07/2008 11:53:00
15   -1  22/07/2008 00:03:00
16   -1  22/07/2008 02:59:00
17   -1  22/07/2008 08:41:00
18   -1  22/07/2008 11:47:00
19   -1  22/07/2008 14:00:00
20   -1  22/07/2008 15:30:00
21   -1  23/07/2008 05:15:00
22   -1  23/07/2008 19:22:00
23    1  25/07/2008 15:23:00
24   -1  27/07/2008 04:18:00
25   -1  27/07/2008 09:37:00
26   -1  27/07/2008 11:10:00
27   -1  27/07/2008 15:46:00
28   -1  27/07/2008 16:06:00
29   -1  27/07/2008 16:49:00
...  ..                  ...
1537 -1  15/10/2008 18:16:00
1538 -1  15/10/2008 19:15:00
1539 -1  15/10/2008 19:24:00
1540 -1  15/10/2008 21:44:00
1541 -1  15/10/2008 22:45:00
1542 -1  15/10/2008 22:54:00
1543 -1  15/10/2008 23:00:00
1544 -1  15/10/2008 23:45:00
1545 -1  16/10/2008 02:16:00
1546 -1  16/10/2008 02:16:00
1547 -1  16/10/2008 02:17:00
1548 -1  16/10/2008 02:22:00
1549 -1  16/10/2008 02:55:00
1550 -1  16/10/2008 03:56:00
1551 -1  16/10/2008 04:02:00
1552 -1  16/10/2008 04:02:00
1553 -1  16/10/2008 04:04:00
1554 -1  16/10/2008 04:47:00
1555 -1  16/10/2008 04:50:00
1556 -1  16/10/2008 04:54:00
1557 -1  16/10/2008 05:08:00
1558 -1  16/10/2008 05:13:00
1559 -1  16/10/2008 05:44:00
1560 -1  16/10/2008 05:58:00
1561 -1  16/10/2008 15:02:00
1562 -1  16/10/2008 15:13:00
1563 -1  16/10/2008 20:49:00
1564 -1  17/10/2008 05:26:00
1565 -1  17/10/2008 06:01:00
1566 -1  17/10/2008 06:07:00

[1567 rows x 2 columns]

In [18]:
secom_y.dtypes

0     int64
1    object
dtype: object

In [20]:
# Coerce datetime column
timestamp = pd.to_datetime(secom_y[1])
timestamp.head()

0   2008-07-19 11:55:00
1   2008-07-19 12:32:00
2   2008-07-19 13:17:00
3   2008-07-19 14:43:00
4   2008-07-19 15:22:00
Name: 1, dtype: datetime64[ns]

## Load JSON Dataset

In [24]:
secom_json = pd.read_json("../data/vendordata.json")
secom_json.head(40)

,adhs vendor,datetime,mat vendor,part vendor,sil vendor,sop vendor
0,bbb,2008-07-19 11:55:00,ddd,aaa,ddd,eee
1,aaa,2008-07-19 12:32:00,eee,ccc,ddd,aaa
10,aaa,2008-07-19 21:57:00,aaa,bbb,eee,eee
100,bbb,2008-08-05 00:04:00,ddd,aaa,fff,eee
1000,bbb,2008-09-22 00:12:00,bbb,ccc,iii,ggg
1001,aaa,2008-09-22 00:28:00,ccc,bbb,hhh,iii
1002,aaa,2008-09-22 00:47:00,bbb,bbb,eee,fff
1003,bbb,2008-09-22 01:43:00,fff,aaa,ccc,kkk
1004,aaa,2008-09-22 03:51:00,bbb,aaa,bbb,iii
1005,aaa,2008-09-22 06:05:00,ccc,bbb,eee,jjj
1006,bbb,2008-09-22 07:12:00,bbb,bbb,ccc,jjj
1007,bbb,2008-09-22 10:43:00,ccc,ccc,eee,fff
1008,aaa,2008-09-22 11:50:00,ddd,ccc,iii,ggg
1009,aaa,2008-09-22 12:11:00,bbb,aaa,fff,ggg
101,bbb,2008-08-05 01:12:00,fff,ccc,ddd,fff
1010,aaa,2008-09-22 12:45:00,fff,aaa,iii,aaa
1011,aaa,2008-09-22 13:03:00,ggg,bbb,ddd,bbb
1012,bbb,2008-09-22 14:24:00,eee,ccc,iii,ccc
1013,bbb,2008-09-22 14:27:00,aaa,ccc,iii,kkk
1014,aaa,2008-09-22 14:36:00,ccc,ccc,iii,bbb
1015,aaa,2008-09-22 16:25:00,ggg,bbb,aaa,hhh
1016,bbb,2008-09-22 21:30:00,aaa,aaa,ddd,iii
1017,aaa,2008-09-22 21:31:00,ccc,aaa,aaa,bbb
1018,aaa,2008-09-22 22:15:00,fff,ccc,eee,ggg
1019,bbb,2008-09-22 22:17:00,eee,aaa,iii,ddd
102,aaa,2008-08-05 02:15:00,eee,bbb,ccc,aaa
1020,aaa,2008-09-22 23:01:00,fff,ccc,eee,eee
1021,bbb,2008-09-22 23:10:00,fff,ccc,ggg,ddd
1022,bbb,2008-09-23 00:57:00,aaa,ccc,bbb,aaa
1023,bbb,2008-09-23 06:44:00,bbb,bbb,fff,ggg
1024,bbb,2008-09-23 06:44:00,fff,bbb,ccc,iii
1025,aaa,2008-09-23 06:52:00,aaa,aaa,iii,ggg
1026,aaa,2008-09-23 07:58:00,ddd,aaa,aaa,fff
1027,aaa,2008-09-23 08:11:00,ccc,aaa,iii,ddd
1028,aaa,2008-09-23 09:43:00,fff,ccc,ccc,hhh
1029,bbb,2008-09-23 11:14:00,fff,aaa,ccc,eee
103,bbb,2008-08-05 02:36:00,fff,aaa,ggg,aaa
1030,aaa,2008-09-23 11:42:00,fff,bbb,hhh,ggg
1031,bbb,2008-09-23 11:43:00,eee,aaa,eee,bbb
1032,aaa,2008-09-23 12:29:00,ccc,aaa,eee,ddd

In [23]:
secom_json.shape

(1567, 6)

In [28]:
secom_json = secom_json.sort_index()

In [29]:
secom_json.head()

  adhs vendor            datetime mat vendor part vendor sil vendor sop vendor
0         bbb 2008-07-19 11:55:00        ddd         aaa        ddd        eee
1         aaa 2008-07-19 12:32:00        eee         ccc        ddd        aaa
2         aaa 2008-07-19 13:17:00        fff         aaa        eee        jjj
3         aaa 2008-07-19 14:43:00        ccc         ccc        hhh        eee
4         bbb 2008-07-19 15:22:00        ccc         bbb        aaa        iii

In [41]:
secom_json["datetime"].apply(lambda d: d.toordinal())

0       733242
1       733242
2       733242
3       733242
4       733242
5       733242
6       733242
7       733242
8       733242
9       733242
10      733242
11      733242
12      733243
13      733244
14      733244
15      733245
16      733245
17      733245
18      733245
19      733245
20      733245
21      733246
22      733246
23      733248
24      733250
25      733250
26      733250
27      733250
28      733250
29      733250
         ...
1537    733330
1538    733330
1539    733330
1540    733330
1541    733330
1542    733330
1543    733330
1544    733330
1545    733331
1546    733331
1547    733331
1548    733331
1549    733331
1550    733331
1551    733331
1552    733331
1553    733331
1554    733331
1555    733331
1556    733331
1557    733331
1558    733331
1559    733331
1560    733331
1561    733331
1562    733331
1563    733331
1564    733332
1565    733332
1566    733332
Name: datetime, Length: 1567, dtype: int64